# Generated by Django 3.0.7 on 2020-12-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('camera_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('access_key_id', models.CharField(max_length=32)),
                ('access_key_secret', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=1024)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cameras', to='login.User')),
            ],
        ),
    ]
