# Generated by Django 3.0.7 on 2020-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20201230_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
