# Generated by Django 3.0.7 on 2020-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_cameras_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='region',
            field=models.CharField(max_length=128),
        ),
    ]
