# Generated by Django 3.0.7 on 2020-12-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_auto_20201230_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameras',
            old_name='username',
            new_name='user',
        ),
    ]
